name: DiscordRelay
main: com.inpuzah.discordRelay.Main
version: ${version}
api-version: "1.20"
author: "You"

# Let Paper fetch JDA + SLF4J binding at runtime (no shading needed)
libraries:
  - net.dv8tion:JDA:5.0.0-beta.24
